services:
  app:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/usr/app/src
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    enviroment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      -${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 1m30s
      timeout: 30s
      retries: 5

volumes:
  pgdata:
